### ISSUE TITLE
Invalid, old steampath causing crash

### ISSUE THREAD

**Issue by yochananmarqos** [geeksville/steamback#10]
What Steam file contains the path it can't find? I switched to using labels and the UUID is no longer pointing to anything.

```
❯ steamback -d
INFO:root:Steamback running...
INFO:root:Storing application data in /home/yochanan/.local/share/steamback
INFO:root:Steamback engine created: Config(logger=<RootLogger root (DEBUG)>, app_data_dir='/home/yochanan/.local/share/steamback', steam_dir='/home/yochanan/.local/share/Steam')
DEBUG:root:Setting account id 19564705 on <steamback.Engine object at 0x7f7f285f5270>
Traceback (most recent call last):
  File "/usr/bin/steamback", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/steamback/__main__.py", line 75, in main
    all_games = e.find_all_game_info()
  File "/usr/lib/python3.10/site-packages/steamback/__init__.py", line 176, in find_all_game_info
    and f.endswith(".acf"), os.listdir(app_dir))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/8144d7d0-b176-461f-8544-1214f7b3ba0a/Games/steam/steamapps'
```

**Comment by rokam** [comment]
Should be fixed by #8

**Comment by yochananmarqos** [comment]
I'm building from the latest commit fd1e716 which contains that, so no it did not.

**Comment by rokam** [comment]
Did you use -s "rightpath"?

**Comment by yochananmarqos** [comment]
No, I did not. I have two Steam libraries. The default `~/.local/share/Steam/` and `/mnt/storage/Games/steam/`. The latter used to be `/mnt/8144d7d0-b176-461f-8544-1214f7b3ba0a/`

**Comment by geeksville** [comment]
@rokam I think this might be a side effect of the new _get_all_library() method.  Could it be that @yochananmarqos's libraryfolders.vdf mentioned this old path and by trying to iterate and read this path with os.files() in file_all_game_info we through an exception.

hmm - I bet we need a try/catch to handle this case and skip bad dirs.  I'll add something.  Thanks @yochananmarqos

**Comment by geeksville** [comment]
@yochananmarqos would you mind confirming that the checkin I just made fixes this for you?

**Comment by yochananmarqos** [comment]
Not quite, it seems:

```
❯ steamback -d
INFO:root:Steamback running...
INFO:root:Storing application data in /home/yochanan/.local/share/steamback
INFO:root:Steamback engine created: Config(logger=<RootLogger root (DEBUG)>, app_data_dir='/home/yochanan/.local/share/steamback', steam_dir='/home/yochanan/.local/share/Steam')
DEBUG:root:Setting account id 19564705 on <steamback.Engine object at 0x7f00b95f51e0>
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/steamback/__init__.py", line 178, in find_all_game_info
    and f.endswith(".acf"), os.listdir(app_dir))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/8144d7d0-b176-461f-8544-1214f7b3ba0a/Games/steam/steamapps'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/steamback", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/steamback/__main__.py", line 75, in main
    all_games = e.find_all_game_info()
  File "/usr/lib/python3.10/site-packages/steamback/__init__.py", line 179, in find_all_game_info
    except e as Exception:
NameError: name 'e' is not defined. Did you mean: 're'?
```

**Comment by geeksville** [comment]
it helps if I write in python not some other language ;-)

**Comment by yochananmarqos** [comment]
That did the trick. :+1:

**Comment by geeksville** [comment]
thx!
