### ISSUE TITLE
Running Steamback in daemon mode crashes with "AttributeError: 'Engine' object has no attribute 'logger'"

### ISSUE THREAD

**Issue by Kyriella** [geeksville/steamback#58]
Running Steamback as a daemon (with either --daemon or -D) results in an error. The output is the same regardless of whether or not I provide a path with --steampath/-s. Steamback was installed through the Arch User Repository (AUR). It runs perfectly fine and backs up games properly when run without using the daemon.
OS: Arch Linux
Kernal: x86_64 Linux 6.5.7-arch1-1
Shell: bash 5.1.16
DE: Xfce4
WM: Xfwm4
Console output (user and host replaced with respective words):
```
user@host ~ $ steamback -D
INFO:root:Steamback running...
INFO:root:Storing application data in /home/user/.local/share/steamback
INFO:root:Steamback engine created: Config(logger=<RootLogger root (INFO)>, app_data_dir='/home/user/.local/share/steamback', steam_dir='/home/user/.local/share/Steam')
WARNING:root:Skipping invalid library directory /run/media/user/Windows 7 Data/Program Files (x86)/Steam/steamapps due to [Errno 2] No such file or directory: '/run/media/user/Windows 7 Data/Program Files (x86)/Steam/steamapps'
Traceback (most recent call last):
  File "/usr/bin/steamback", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/steamback/__main__.py", line 84, in main
    asyncio.run(d.run_forever())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/steamback/util.py", line 98, in run_forever
    self.engine.logger.info(
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'logger'

```

**Comment by geeksville** [comment]
interesting thanks!  I'll address this sometime soonish hopefully.
