### ISSUE TITLE
Steamback desktop stopped saving games

### ISSUE THREAD

**Issue by JustCryen** [geeksville/steamback#87]
Last save I have is from 5 months ago but I don't always use steamback while playing games.

The problem currently is with Hellblade: Senua's sacrifice, Steamback gives me an option to undo changes to this game but it does not save any new states of the game.  
So it must be aware that the game stopped running but it does not add a new state of the game to the saved list.

This is the error thrown when running Steamback through the terminal:

```
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-16' coro=<GUI.watch_steam() done, defined at /home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/steamback/gui.py:293> exception=psutil.ZombieProcess(pid=3889, msg="PID still exists but it's a zombie")>
Traceback (most recent call last):
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/steamback/gui.py", line 295, in watch_steam
    result = await self.watcher.check_once()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/steamback/util.py", line 78, in check_once
    running = set(find_running_games())
                  ^^^^^^^^^^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/steamback/util.py", line 53, in find_running_games
    id = get_game_id(proc)
         ^^^^^^^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/steamback/util.py", line 42, in get_game_id
    line = p.cmdline()
           ^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/psutil/__init__.py", line 719, in cmdline
    return self._proc.cmdline()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/psutil/_pslinux.py", line 1714, in wrapper
    return fun(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/psutil/_pslinux.py", line 1853, in cmdline
    self._raise_if_zombie()
  File "/home/cryen/.local/share/pipx/venvs/steamback/lib/python3.12/site-packages/psutil/_pslinux.py", line 1758, in _raise_if_zombie
    raise ZombieProcess(self.pid, self._name, self._ppid)
psutil.ZombieProcess: PID still exists but it's a zombie (pid=3889)
```

![Screenshot From 2024-12-08 19-24-48.png](https://github.com/user-attachments/assets/82cff5a8-c221-4516-b71d-83ba505879e9)

**OS**: ArchLinux
**Kernel**: 6.12.1-zen1-1-zen
**Steam version**: 1733265492 Stable Client
**Installation type**: I have tried installing it through AUR as well as from PIP but the behaviour is the same in both cases.

**Comment by JustCryen** [comment]
Same issue, different (fresh) system.  

First time I have used it, Sable actually backed up the save state once, then I restarted the game, played for a bit and closed again.  
No game save on steamback this time.  
Code lines have changed a bit so I will paste the terminal output once more.

```
INFO:root:Attempting backup of {'install_root': '/home/cryen/.local/share/Steam', 'game_id': 757310, 'game_name': 'Sable', 'save_games_roots': {'/home/cryen/.local/share/Steam/steamapps/compatdata/757310/pfx/drive_c/users/steamuser/AppData/LocalLow': ''}}
INFO:root:Copied 5 files from /home/cryen/.local/share/Steam/steamapps/compatdata/757310/pfx/drive_c/users/steamuser/AppData/LocalLow to /home/cryen/.local/share/steamback/saves2/save_757310_1756762073929
ERROR:asyncio:Task exception was never retrieved
future: <Task finished name='Task-25' coro=<GUI.watch_steam() done, defined at /usr/lib/python3.13/site-packages/steamback/gui.py:293> exception=psutil.ZombieProcess(pid=43178, msg="PID still exists but it's a zombie")>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/steamback/gui.py", line 295, in watch_steam
    result = await self.watcher.check_once()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/steamback/util.py", line 78, in check_once
    running = set(find_running_games())
                  ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/steamback/util.py", line 53, in find_running_games
    id = get_game_id(proc)
  File "/usr/lib/python3.13/site-packages/steamback/util.py", line 42, in get_game_id
    line = p.cmdline()
  File "/usr/lib/python3.13/site-packages/psutil/__init__.py", line 739, in cmdline
    return self._proc.cmdline()
           ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/psutil/_pslinux.py", line 1646, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/psutil/_pslinux.py", line 1790, in cmdline
    self._raise_if_zombie()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/psutil/_pslinux.py", line 1693, in _raise_if_zombie
    raise ZombieProcess(self.pid, self._name, self._ppid)
psutil.ZombieProcess: PID still exists but it's a zombie (pid=43178)
```
**OS:** EndeavourOS
**Kernel:** 6.16.3-zen1-1-zen
**Steam version:** 1751405894 Stable Client
**Installation type:** AUR (steamback desktop)
